### ISSUE TITLE
Set up protection for main branch

### ISSUE THREAD

**Issue by simeeid** [simeeid/TDT4290Group1#13]
- [x] Protect main from direct push
- [x] Add review requirement for merge to main
- [x] Add compilation requirement for merge to main

Definition of done: completed when impossible to push directly into main, and only possible to merge with main after review and successful compilation of branch
